/**
 * Copy the WGSL this decoder dispatches out of web-xpu-ops and into `kernels.ts`.
 *
 *     node gen-kernels.mjs
 *
 * Same reasoning as `spike/miocodec/gen-kernels.mjs`: the source has to load
 * under esbuild's bundle and in a browser, and each has its own spelling for
 * "import this file as text". One generated module is understood by both.
 *
 * Unlike the two older spikes, this reads from the **installed package** rather
 * than a `file:` checkout. `web-xpu-ops` is on npm now (0.2.0), so the version
 * a kernel came from is a thing `package-lock.json` already records, and there
 * is no local clone to drift against.
 */

import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const packageJson = require.resolve("web-xpu-ops/package.json");
const UPSTREAM = dirname(packageJson);
const version = JSON.parse(readFileSync(packageJson, "utf8")).version;

/**
 * The three the decode path dispatches, and nothing else. Contracts are copied
 * from each kernel's own header — the binding order and the uniform field
 * order are the authority there, and nothing below is re-derived.
 */
const KERNELS = [
  {
    name: "SNAKE",
    op: "snake",
    entry: "kernel",
    contract: [
      "bindings: [input f32 [N, C, L], alpha f32 [C], out f32 [N, C, L], uniform]",
      "uniform:  [u32 N, u32 C, u32 L]  (padded to 16 bytes)",
      "dispatch: [ceil(N*C*L / 256)]",
      "The one-parameter form: x + (1/(alpha_c + 1e-9)) * sin(alpha_c * x)^2.",
      "alpha is per CHANNEL, indexed as (idx / L) % C.",
    ],
  },
  {
    name: "CONV1D",
    op: "conv",
    entry: "kernel",
    contract: [
      "bindings: [input f32 [N, Cin, L], weight f32 [Cout, Cin/groups, K],",
      "           bias f32 [Cout] (required — an unreferenced binding throws),",
      "           out f32 [N, Cout, Lout], uniform]",
      "uniform:  [u32 Cin, Cout, L, K, Lout, stride, padding, dilation,",
      "           in_per_group, out_per_group, reserved_0, reserved_1]",
      "dispatch: [ceil(Lout / 256), Cout, N]",
    ],
  },
  {
    name: "ACTIVATION",
    op: "activation",
    entry: "kernel",
    contract: [
      "bindings: [input f32 [N], out f32 [N], uniform]",
      "uniform:  [u32 N, u32 activation_type, f32 alpha]",
      "dispatch: [ceil(N / 256)]",
      "Only kind 3 (tanh) is used here — the decoder's output tail.",
      "`decoder.ts` spells it `Float32Array.from(x, Math.tanh)`, which a path",
      "that never touches a Float32Array cannot.",
    ],
  },
  {
    name: "ELEMENTWISE",
    op: "elementwise",
    entry: "kernel",
    contract: [
      "bindings: [a f32 [N], b f32 [N], out f32 [N], uniform]",
      "uniform:  [u32 N, u32 kind]   (0 = add, 1 = multiply)",
      "dispatch: [ceil(N / 256)]",
      "The residual unit's add. `decoder.ts` does it in JavaScript because it",
      "reads a Float32Array; `decode-gpu.ts` cannot, and should not.",
    ],
  },
  {
    name: "CONV_TRANSPOSE1D",
    op: "conv_transpose",
    entry: "kernel",
    contract: [
      "bindings: [input f32 [N, Cin, L], weight f32 [Cin, Cout/groups, K],",
      "           bias f32 [Cout], out f32 [N, Cout, Lout], uniform]",
      "uniform:  same twelve fields as conv, same order.",
      "          output_padding is NOT a field: it only lengthens the output,",
      "          so the host folds it into Lout and the kernel writes zeros",
      "          where no input contributes.",
      "dispatch: [ceil(Lout / 256), Cout, N]",
      "weight is [Cin, Cout, K] here, the transpose of conv's layout.",
    ],
  },
];

const parts = [
  "// Generated by gen-kernels.mjs — do not edit.",
  `// Source: web-xpu-ops @ ${version} (from node_modules, pinned by package-lock.json)`,
  "//",
  "// WGSL for the kernel entry points the DACVAE codec path dispatches.",
  "// Every contract comment below is copied from the kernel's own header, which",
  "// is the authority for binding and uniform order; nothing is re-derived.",
  "// All entry points are `fn main`.",
  "",
];

for (const { name, op, entry, contract } of KERNELS) {
  const source = readFileSync(join(UPSTREAM, "dist", "ops", op, "wgsl", `${entry}.wgsl`), "utf8");
  parts.push("/**");
  parts.push(` * ops/${op}/wgsl/${entry}.wgsl`);
  parts.push(" *");
  for (const line of contract) parts.push(` * ${line}`);
  parts.push(" */");
  // `JSON.stringify` rather than a template literal: these kernels carry prose
  // comments and backticks. Escaping by hand is a rule someone has to
  // remember; quoting is a rule nobody can forget.
  parts.push(`export const ${name} = ${JSON.stringify(source)};`);
  parts.push("");
}

parts.push(`export const UPSTREAM_VERSION = ${JSON.stringify(version)};`);
parts.push("");

const out = new URL("./kernels.ts", import.meta.url).pathname;
writeFileSync(out, parts.join("\n"));
console.log(`wrote ${out} from web-xpu-ops @ ${version}`);
