/**
 * Copy the WGSL this port dispatches out of web-xpu-ops and into `kernels.ts`.
 *
 *     node gen-kernels.mjs
 *
 * Why generate a TypeScript file rather than importing the `.wgsl` directly:
 * the same source has to load under Vitest, under esbuild's bundle, and in a
 * browser, and each has its own spelling for "import this file as text"
 * (`?raw`, `--loader:.wgsl=text`, `fetch`). One generated module is understood
 * by all three and keeps the demo a single self-contained bundle.
 *
 * The output is committed, and this script is how it is rebuilt. It records the
 * commit it was taken from, so a kernel that has moved on upstream is visible
 * rather than silently stale.
 */

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const UPSTREAM = new URL("../../../web-xpu-ops/", import.meta.url).pathname;

/** Only what this decoder actually dispatches. */
const KERNELS = [
  { name: "MATMUL", op: "matmul", entry: "kernel" },
  { name: "CONV1D", op: "conv", entry: "kernel" },
  { name: "ISTFT", op: "stft", entry: "inverse" },
];

const revision = execFileSync("git", ["-C", UPSTREAM, "rev-parse", "--short", "HEAD"], {
  encoding: "utf8",
}).trim();

const parts = [
  "// Generated by gen-kernels.mjs — do not edit.",
  `// Source: web-xpu-ops @ ${revision}`,
  "//",
  "// WGSL for the three ops this port dispatches on the GPU. Everything else in",
  "// the graph runs on the reference implementations, because everything else is",
  "// linear in the data and these three are not: matmul, conv1d and the inverse",
  "// transform are where the arithmetic actually is.",
  "",
];

for (const { name, op, entry } of KERNELS) {
  const path = join(UPSTREAM, "ops", op, "wgsl", `${entry}.wgsl`);
  const source = readFileSync(path, "utf8");
  // `JSON.stringify` rather than a template literal: these kernels carry
  // prose comments, and `ops/matmul` already contains a backtick. Escaping by
  // hand is a rule someone has to remember; quoting is a rule nobody can
  // forget.
  parts.push(`/** ops/${op}/wgsl/${entry}.wgsl */`);
  parts.push(`export const ${name} = ${JSON.stringify(source)};`);
  parts.push("");
}

parts.push(`export const UPSTREAM_REVISION = ${JSON.stringify(revision)};`);
parts.push("");

const out = new URL("./kernels.ts", import.meta.url).pathname;
writeFileSync(out, parts.join("\n"));
console.log(`wrote ${out} from web-xpu-ops @ ${revision}`);
