/**
 * Copy the WGSL this engine dispatches out of web-xpu-ops and into `kernels.ts`.
 *
 *     node gen-kernels.mjs
 *
 * Why generate a TypeScript file rather than importing the `.wgsl` directly
 * (same reasoning as spike/miocodec/gen-kernels.mjs): the same source has to
 * load under esbuild's bundle and in a browser, and each has its own spelling
 * for "import this file as text" (`--loader:.wgsl=text`, `fetch`). One
 * generated module is understood by both and keeps the page a single
 * self-contained bundle.
 *
 * The output is committed, and this script is how it is rebuilt. It records the
 * commit it was taken from, so a kernel that has moved on upstream is visible
 * rather than silently stale.
 */

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const UPSTREAM = new URL("../../../web-xpu-ops/", import.meta.url).pathname;

/**
 * Only what the Qwen3 decode path dispatches. The `contract` lines are the
 * binding order and uniform field order **copied from web-xpu-ops'
 * `llm/kernels.ts` wrappers** (which copied them from each op's own
 * `wgsl.test.ts`) — that file is the authority; nothing here is re-derived.
 */
const KERNELS = [
  {
    name: "MATVEC_Q8",
    op: "matvec",
    entry: "q8",
    contract: [
      "bindings: [weight u32 [M, ceil(K/4)] (4 sign-extended int8 codes per word, LSB first),",
      "           scale f32 [M], vector f32 [K], out f32 [M], uniform]",
      "uniform:  [u32 M, u32 K]",
      "dispatch: [M] — one workgroup per output row; chunk when M > 65535",
      "          (maxComputeWorkgroupsPerDimension), see llm/kernels.ts#MAX_WORKGROUPS_PER_DISPATCH.",
    ],
  },
  {
    name: "RMSNORM",
    op: "rmsnorm",
    entry: "kernel",
    contract: [
      "bindings: [input f32 [N, D], weight f32 [groups, D], out f32 [N, D], uniform]",
      "uniform:  [u32 N, u32 D, f32 eps, u32 groups]  (groups=1: one shared gamma)",
      "dispatch: [N] — one workgroup per row.",
    ],
  },
  {
    name: "ROPE",
    op: "rope",
    entry: "kernel",
    contract: [
      "bindings: [input f32 [N, heads, headDim] token-major, cache (dummy, 2 f32,",
      "           unread when cache_positions=0), out f32 (same shape), uniform]",
      "uniform:  [u32 N, u32 num_heads, u32 head_dim, u32 pos_offset, u32 cache_positions,",
      "           f32 effective_base, f32 interpolation_factor, f32 ramp_low, f32 ramp_high,",
      "           f32 attention_factor, u32 head_offset, u32 head_count]",
      "          pos_offset is field index 3 (byte 12) — rewritten per decode step.",
      "dispatch: [ceil(N*heads*headDim/2 / 256)] — adjacent-pair rotation (NOT HF rotate-half;",
      "          the q8 artifacts' wq/wk rows and qNorm/kNorm gammas are already permuted for it).",
    ],
  },
  {
    name: "GQA_SCORES",
    op: "gqa",
    entry: "scores",
    contract: [
      "bindings: [q f32 [B,H,L,D] head-major, k f32 [B,kvHeads,S,D], mask f32 [B*S] (all-zero",
      "           bias here), probs out f32 [B,H,L,S], uniform]",
      "uniform:  [u32 H, u32 kvHeads, u32 L, u32 S, u32 D, f32 scale, u32 causal,",
      "           i32 query_offset, u32 B, u32 1, u32 1, u32 s_eff]",
      "          query_offset is index 7 (byte 28), s_eff index 11 (byte 44) — both rewritten",
      "          per decode step to `at` and `at + 1`. S stays maxSeqLen (the cache stride).",
      "dispatch: [L, H, B]",
    ],
  },
  {
    name: "GQA_CONTEXT",
    op: "gqa",
    entry: "context",
    contract: [
      "bindings: [probs f32 [B,H,L,S], v f32 [B,kvHeads,S,Dv], out f32 [B,H,L,Dv], uniform]",
      "uniform:  [u32 H, u32 kvHeads, u32 L, u32 S, u32 Dv, u32 s_eff]",
      "          s_eff is index 5 (byte 20) — must agree with GQA_SCORES' s_eff every step.",
      "dispatch: [L, H, B]",
    ],
  },
  {
    name: "ACTIVATION",
    op: "activation",
    entry: "kernel",
    contract: [
      "bindings: [input f32 [N], out f32 [N], uniform]",
      "uniform:  [u32 N, u32 kind, f32 alpha]  (kind: ops/activation ACTIVATION — silu = 1)",
      "dispatch: [ceil(N / 256)]",
    ],
  },
  {
    name: "ELEMENTWISE",
    op: "elementwise",
    entry: "kernel",
    contract: [
      "bindings: [a f32 [N], b f32 [N], out f32 [N], uniform]",
      "uniform:  [u32 N, u32 kind]  (kind: ops/elementwise ELEMENTWISE — add = 0, multiply = 1)",
      "dispatch: [ceil(N / 256)]",
    ],
  },
];

const revision = execFileSync("git", ["-C", UPSTREAM, "rev-parse", "--short", "HEAD"], {
  encoding: "utf8",
}).trim();

const parts = [
  "// Generated by gen-kernels.mjs — do not edit.",
  `// Source: web-xpu-ops @ ${revision}`,
  "//",
  "// WGSL for the seven kernel entry points the Qwen3 q8 decode engine",
  "// (gpu-engine.ts) dispatches. Every contract comment below is copied from",
  "// web-xpu-ops' llm/kernels.ts wrappers (the binding order / uniform field",
  "// order authority, themselves copied from each op's wgsl.test.ts), never",
  "// re-derived. All entry points are `fn main`.",
  "",
];

for (const { name, op, entry, contract } of KERNELS) {
  const path = join(UPSTREAM, "ops", op, "wgsl", `${entry}.wgsl`);
  const source = readFileSync(path, "utf8");
  // `JSON.stringify` rather than a template literal: these kernels carry prose
  // comments and backticks. Escaping by hand is a rule someone has to
  // remember; quoting is a rule nobody can forget.
  parts.push("/**");
  parts.push(` * ops/${op}/wgsl/${entry}.wgsl`);
  parts.push(" *");
  for (const line of contract) parts.push(` * ${line}`);
  parts.push(" */");
  parts.push(`export const ${name} = ${JSON.stringify(source)};`);
  parts.push("");
}

parts.push(`export const UPSTREAM_REVISION = ${JSON.stringify(revision)};`);
parts.push("");

const out = new URL("./kernels.ts", import.meta.url).pathname;
writeFileSync(out, parts.join("\n"));
console.log(`wrote ${out} from web-xpu-ops @ ${revision}`);
